DROP DATABASE IF EXISTS management_db;
CREATE DATABASE management_db;
USE management_db;

DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Departments;
DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS Budgets;

CREATE TABLE Departments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Department VARCHAR(50) NOT NULL
);


CREATE TABLE Roles (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  Title VARCHAR(30) NOT NULL,
  Salary DECIMAL(10, 2) NOT NULL,
  Department_id INT NOT NULL,
  FOREIGN KEY (Department_id) REFERENCES Departments(id) ON DELETE CASCADE
);

CREATE TABLE Employees (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  First_Name VARCHAR(30) NOT NULL,
  Last_Name VARCHAR(30) NOT NULL,
  Role_id INT,
  Manager_id INT,
  FOREIGN KEY (Role_id) REFERENCES Roles(id) ON DELETE CASCADE,
  FOREIGN KEY (Manager_id) REFERENCES Employees(id)
);


CREATE TABLE Budgets (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  Department_id INT NOT NULL,
  Amount DECIMAL(12, 2) NOT NULL,
  FOREIGN KEY (Department_id) REFERENCES Departments(id) ON DELETE CASCADE
);